[build]
	command = "npx pnpm build"
	publish = "dist"

[build.environment]
	NODE_VERSION = "16"
	NPM_FLAGS = "--version" # prevent auto npm install

[build.processing]
	skip_processing = true

[[plugins]]
	package = "./plugins/pnpm-preinstaller"

[[redirects]]
	from = "/full"
	to = "/?full"
	status = 301

[[redirects]]
	from = "/small"
	to = "/?small"
	status = 301

[[redirects]]
	from = "/404"
	to = "/?404"
	status = 301

[[redirects]]
	from = "/*"
	to = "/?404"
	status = 301